export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESSFUL = 'SEARCH_SUCCESSFUL';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const AUTO_SEARCH = 'AUTO_SEARCH';